language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - sudo apt-get install gcc-multilib g++-multilib
  - sudo apt-get install gdb

install:
  - phpenv config-add .travis.php.ini
  - composer install --no-interaction --no-progress --no-suggest

script:
  - composer run-script test
  - composer run-script build
