build: false
clone_folder: C:\projects\deplink

image:
  - Visual Studio 2017

platform:
  - x64

init:
  - cinst php
  - cinst composer

  # Install TDM64 which supports both -m32 and -m64 gcc flag
  # (flags used to compiler application for x86 and x64 arch).
  - mkdir "c:\tdm64"
  - appveyor DownloadFile "https://kent.dl.sourceforge.net/project/tdm-gcc/TDM-GCC 5 series/5.1.0-tdm64-1/gcc-5.1.0-tdm64-1-core.zip" -FileName "c:\gcc-5.1.0-tdm64-1-core.zip"
  - 7z x -y "c:\gcc-5.1.0-tdm64-1-core.zip" -o"c:\tdm64"
  - appveyor DownloadFile "https://kent.dl.sourceforge.net/project/tdm-gcc/GNU binutils/binutils-2.25-tdm64-1.zip" -FileName "c:\binutils-2.25-tdm64-1.zip"
  - 7z x -y "c:\binutils-2.25-tdm64-1.zip" -o"c:\tdm64"
  - appveyor DownloadFile "https://kent.dl.sourceforge.net/project/tdm-gcc/MinGW-w64 runtime/GCC 5 series/mingw64runtime-v4-git20150618-gcc5-tdm64-1.zip" -FileName "c:\mingw64runtime-v4-git20150618-gcc5-tdm64-1.zip"
  - 7z x -y "c:\mingw64runtime-v4-git20150618-gcc5-tdm64-1.zip" -o"c:\tdm64"
  - appveyor DownloadFile "https://kent.dl.sourceforge.net/project/tdm-gcc/TDM-GCC 5 series/5.1.0-tdm64-1/gcc-5.1.0-tdm64-1-c++.zip" -FileName "c:\gcc-5.1.0-tdm64-1-c++.zip"
  - 7z x -y "c:\gcc-5.1.0-tdm64-1-c++.zip" -o"c:\tdm64"

  # Add PHP, Composer and TDM to the PATH variable
  # (globally accessible, especially gcc for deplink).
  - set PATH=%PATH%;c:\tdm64\bin;C:\ProgramData\ComposerSetup\bin;C:\tools\php
  - echo %PATH%

  # Enable creating phar archives in PHP (required by test_script).
  # Script replaces the ";phar.readonly = On" to "phar.readonly = Off" in php.ini.
  - ps: (Get-Content 'C:\tools\php\php72.ini').replace(';phar.readonly = On', 'phar.readonly = Off') | Set-Content 'C:\tools\php\php72.ini'

  # Print versions for easier diagnostics.
  - gcc --version
  - g++ --version
  - php --version

install:
  - composer install --no-interaction --no-progress --no-suggest

test_script:
  - composer run-script test
  - composer run-script build
