build: false
clone_folder: C:\projects\deplink

image:
  - Visual Studio 2015

platform:
  - x86
  - x64

init:
  - SET PATH=C:\MinGW\bin;%PATH%

install:
  - cinst php --version 7.0.1 --allow-empty-checksums
  - cinst composer --version 4.7.0 --allow-empty-checksums
  - refreshenv
  - cd C:\projects\deplink
  - composer install --no-interaction --no-progress --no-suggest
  - gcc --version

test_script:
  - composer run-script test
  - composer run-script build
