build: false
clone_folder: C:\projects\deplink

image:
  - Visual Studio 2017

platform:
  - x86
  - x64

init:
  - cinst php --version 7.0.1 --allow-empty-checksums
  - cinst composer --version 4.7.0 --allow-empty-checksums
  - refreshenv
  - php --version

  - mkdir "c:\tdm64"
  - curl -fsSL -o "c:\gcc-5.1.0-tdm64-1-core.zip" -m 180 "https://kent.dl.sourceforge.net/project/tdm-gcc/TDM-GCC%205%20series/5.1.0-tdm64-1/gcc-5.1.0-tdm64-1-core.zip"
  - 7z e -r -y "c:\gcc-5.1.0-tdm64-1-core.zip" -o"c:\tdm64"
  - curl -fsSL -o "c:\binutils-2.25-tdm64-1.zip" -m 180 "https://kent.dl.sourceforge.net/project/tdm-gcc/GNU%20binutils/binutils-2.25-tdm64-1.zip"
  - 7z e -r -y "c:\binutils-2.25-tdm64-1.zip" -o"c:\tdm64"
  - curl -fsSL -o "c:\mingw64runtime-v4-git20150618-gcc5-tdm64-1.zip" -m 180 "https://kent.dl.sourceforge.net/project/tdm-gcc/MinGW-w64%20runtime/GCC%205%20series/mingw64runtime-v4-git20150618-gcc5-tdm64-1.zip"
  - 7z e -r -y "c:\mingw64runtime-v4-git20150618-gcc5-tdm64-1.zip" -o"c:\tdm64"
  - curl -fsSL -o "c:\gcc-5.1.0-tdm64-1-c%2B%2B.zip" -m 180 "https://kent.dl.sourceforge.net/project/tdm-gcc/TDM-GCC%205%20series/5.1.0-tdm64-1/gcc-5.1.0-tdm64-1-c%2B%2B.zip"
  - 7z e -r -y "c:\gcc-5.1.0-tdm64-1-c%2B%2B.zip" -o"c:\tdm64"

  - setx PATH "%PATH%;c:\tdm64"
  - refreshenv
  - echo %PATH%
  - php --version

install:
  - composer install --no-interaction --no-progress --no-suggest

test_script:
  - composer run-script test
  - composer run-script build
